FROM python:3.9

COPY requirements.airflow.txt requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

COPY src/ml/ /app/
WORKDIR /app

ENTRYPOINT [ "python", "train_evaluate.py" ]